/**
 * design-system/lucent/tokens.json  ->  styles/tokens.css
 *
 * tokens.json is the Lucent kit's source of truth. The tokens.css the kit
 * publishes alongside it is generated by the design-system page and can lag a
 * version behind (it did at v6: stale spring values, retired wall-* colours),
 * so the site builds its own from the JSON instead of copying that file.
 *
 * It also adds what the kit's file leaves out: dark mode that follows the OS.
 * The kit only switches on [data-theme="dark"]; here the dark values apply under
 * prefers-color-scheme too, unless the page pins [data-theme="light"].
 *
 * Runs before `dev` and `build` (see package.json). Never edit tokens.css by hand.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'design-system/lucent/tokens.json');
const out = join(root, 'styles/tokens.css');
const t = JSON.parse(readFileSync(src, 'utf8'));

const themes = t.color.themes.map((th) => th.id);
const [primary, ...others] = themes;

/** One line per token, with its usage note kept as the comment. */
const line = (name, value, usage) =>
  `  --${name}: ${value};${usage ? ` /* ${usage.replace(/\*\//g, '* /')} */` : ''}`;

/** Themed families: colour, and any family whose values are per-theme objects (shadow). */
const themed = [...t.color.tokens, ...(t.shadow?.tokens ?? [])];
const valueFor = (tok, theme) =>
  typeof tok.value === 'string' ? tok.value : (tok.value[theme] ?? tok.value[primary]);

const block = (theme, withUsage) =>
  themed.map((tok) => line(tok.name, valueFor(tok, theme), withUsage && tok.usage)).join('\n');

/** Plain families: one value for every theme. */
const plainFamilies = ['spacing', 'radius', 'material', 'duration', 'easing', 'spring', 'layer'];
const plain = plainFamilies
  .flatMap((f) => t[f]?.tokens ?? [])
  .map((tok) => line(tok.name, tok.value, tok.usage))
  .join('\n');

/** Type: families as --font-*, each style as a --text-* shorthand and a utility class. */
const fam = Object.entries(t.type.families)
  .map(([k, v]) => `  --font-${k}: ${v};`)
  .join('\n');
const styles = t.type.groups.flatMap((g) => g.styles.map((s) => ({ ...s, family: g.family })));
const shorthands = styles
  .map((s) =>
    line(`text-${s.name}`, `${s.fontWeight} ${s.fontSize}/${s.lineHeight} var(--font-${s.family})`, s.usage),
  )
  .join('\n');
const classes = styles
  .map(
    (s) => `.${s.name} {
  font-family: var(--font-${s.family});
  font-size: ${s.fontSize};
  line-height: ${s.lineHeight};
  font-weight: ${s.fontWeight};
  letter-spacing: ${s.letterSpacing ?? 0};
}`,
  )
  .join('\n');

const dark = others.includes('dark') ? 'dark' : others[0];

const css = `/* ${t.name} v${t.version} — GENERATED from design-system/lucent/tokens.json by scripts/build-tokens.mjs. Do not edit. */

:root,
:root[data-theme="${primary}"] {
  color-scheme: ${primary};
${block(primary, true)}
}
${
  dark
    ? `
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="${primary}"]) {
    color-scheme: ${dark};
${block(dark, false).replace(/^/gm, '  ')}
  }
}

:root[data-theme="${dark}"] {
  color-scheme: ${dark};
${block(dark, false)}
}
`
    : ''
}
:root {
${plain}
${fam}
${shorthands}
}

${classes}
`;

writeFileSync(out, css);
console.log(`tokens: ${themed.length} themed + ${plainFamilies.length} families -> ${out.replace(root + '/', '')}`);
